# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b2251f3bff633c8fa34188f37075674532fafa71b2676c42b91c7c69ae0f55891264c2b704a4025cfdb59bf0b7f3cca824b97504757c3469d783f4c739afa12

test:
  secret_key_base: 6b10fd663f999c6651536addfe413cf295064a41fd42a5375f6b99be51052996288a027de3a9b634421d197a270012f2eb4b24c3fc633df5aeb8bfc82bd9e3fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
